### PR TITLE
#88 Create order fixes

### LINKED ISSUE #88: UI: Create/edit order bugs
- totals after loading page NaN for a second
- round total, vat (2 digits)

Image

---------------------------
Case: --- **Fixed**
- create order without vat
- open order to edit

Expected 
- netto = brutto

Actual
- netto != brutto
brutto calculated with vat

---------------------------

The order task name is not readable --- **Fixed**

---------------------------

Localization for `Vat is turned off` string

_______________________

Margins for oder task vat/netto/brutto

### PR DESCRIPTION
**Pull request by kolodgeeva**
#88 Round totals, add margins for total tags
image

### CODE REVIEW

File: src/components/pages/orders/CreateOrderForm.vue [hunk 1]
```diff
@@ -392,7 +386,9 @@ const calculateTotal = (row: any) => {
                         </VIconBox>
                       </div>
                       <div class="tile-body">
-                        <span class="dark-inverted">{{ totalData.totalBrutto }}</span>
+                        <span class="dark-inverted">{{
+                          totalData.totalBrutto.toFixed(2)
```
Comment (EvgeniyGelfman) [inline src/components/pages/orders/CreateOrderForm.vue:390]: Let's store totalData already with rounded values
